FROM centos
LABEL name="Metwork install dependancies" desc="Intall dependancies for Metwork modules" version="1.0"

RUN yum -y install gcc \
                   gcc-c++ \
                   gettext \
                   git \
                   libffi-devel \
                   make \
                   openssl-devel \
                   patch \
                   readline-devel \
                   wget \
                   zlib-devel
